# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 00:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_auto_20170824_2314'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='comment',
            managers=[
                ('positive_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='thumb',
            managers=[
                ('up_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='video',
            name='views',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
