# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 02:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_auto_20170825_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='thumb',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='themes',
            field=models.ManyToManyField(related_name='videos', to='videos.Theme'),
        ),
    ]
