# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 10:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_auto_20170825_0209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='file',
        ),
        migrations.AlterField(
            model_name='comment',
            name='time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='thumb',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
